### ISSUE TITLE
Hide the process exit code line

### ISSUE THREAD

**Issue by RobertAudi** [Drieam/rspec-github#14]
When some tests fail one of the failure is `Process completed with exit code 1.`. There is an example in [a failed run](https://github.com/Drieam/rspec-github/actions/runs/322402219) in this repo.

<img width="359" alt="CleanShot 2022-03-06 at 15 29 16@2x" src="https://user-images.githubusercontent.com/87562/156927563-bd47bb5d-94f2-4af1-81e9-94f1451bfd8d.png">

Is it possible to hide this line from the annotations?

**Comment by StefSchenkelaars** [comment]
@RobertAudi I haven't tested it but I assume that if you change the exit code to pass, that the GitHub actions mark the full action as passed. 

And next to this, the exid code is not defined by this formatter but rather the command itself. If you want your command to succeed, you can allways append `|| true` to your command. So for example:

```
bundle exec rspec || true
```

Hope this helps. And feel free to update the README with this information 👍

**Comment by RobertAudi** [comment]
@StefSchenkelaars I just tried your suggestion and added `|| true` to the commands.

You are correct that if the exit code it changed to pass then the GitHub action marks the full action as passed, so added `|| true` will not only hide the exit code but also all the failures 😕 

Il will try to investigate a bit more but as of now I don't think there is a solution to the problem.
